LANG[0]="Aooo üzgünüm ama bu araç Super user(root) yetkilerine ihtiyaç duymaktadır lütfen şöyle deneyin \n sudo $0"
LANG[1]="DİL:${lang^^}"
LANG[2]="TAMAMDIR"
LANG[3]="EKSİK"
LANG[4]="AOOO SANIRSAM BAZI PAKETLER EKSİK İNDİRMEK İSTER MİSİN ? EKSİK OLAN PAKET :$tool"
LANG[5]="BÜTÜN GEREKLİLİKLER ${COLOR_ARRAY[1]}TAMAM ${COLOR_ARRAY[5]} ${COLOR_ARRAY[4]} ARAÇ BAŞARILI BİR ŞEKİLDE ${COLOR_ARRAY[3]} ÇALIŞABİLİR"
LANG[6]="GÜZEL ROOT YETKİLERİ SAĞLANDI"